export const RETRY_DELAYS = [30, 120, 600];
export const STATUS = {
  NOT_STARTED: "NOT_STARTED",
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  PARTIAL: "PARTIAL"
};

export const PERIODS = ["MONTHLY", "QUARTERLY", "ANNUAL"];
export const COMMISSION_RATE = 0.25;
export const CONVERSATIONS_PER_BUYER = 3;
export const MINUTES_PER_CONVERSATION = 10;
export const DAYS_PER_WEEK = 6;
export const INTERVIEW_STATUS = {
  NOT_SCHEDULED: 'NOT_SCHEDULED',
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
};
export const ONBOARDING_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  SHARED_FOR_REVIEW: 'SHARED_FOR_REVIEW'
};
